services:
  app:
    build: .
    container_name: todo_app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=iir4
      - MYSQL_DATABASE=todo_db
    command: sh -c "yarn install && yarn run dev"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=iir4
      - MYSQL_DATABASE=todo_db
    volumes:
      - todo-mysql-data:/var/lib/mysql

volumes:
  todo-mysql-data:
    driver: local
